# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c582ca416dd4a6bbe13fb16d2a17fe5769a52f735da2622ae0429cd84128699c55335c609484b66de80a529fbb74522026984aad41956173f4803311a998dfc

test:
  secret_key_base: e6fe739e04736c8f14d34faf472d0f5958ff820257ca43ed63b3d308530ca1123db8a3893200d65687b76f4320f366bdaec0d1819590233bfb9b4a5b7544a21b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
